const projects = [
    {
        id: 1,
        name: "Short North Map Redo",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-02-10",
        category: "Work - Safety",
        objective: "Completed Projects",
        notes: "Created a new map design for the Short North location focusing on improved navigation and safety protocols",
        completion: 100
    },
    {
        id: 2,
        name: "Sunny Homepage",
        status: "Ongoing",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-02-15",
        category: "Work - Web Dev",
        objective: "Create engaging homepage for Sunny the Safety Duck",
        notes: "Developing interactive homepage with Sunny character, safety tips, and team engagement features",
        completion: 85
    },
    {
        id: 3,
        name: "Safety Banner",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-01-15",
        category: "Work - Safety",
        objective: "Create prominent safety messaging banner",
        notes: "Developed dynamic safety banner with rotating messages, emergency protocols, and visual safety reminders",
        completion: 100
    },
    {
        id: 4,
        name: "Committee Files",
        status: "Completed",
        priority: "Medium",
        type: "Safety",
        startDate: "2025-01-10",
        category: "Work - Safety",
        objective: "Organize safety committee documentation",
        notes: "Compiled and organized all safety committee meeting minutes, protocols, and action items",
        completion: 100
    },
    {
        id: 5,
        name: "Sunny's Safety Tips",
        status: "Completed",
        priority: "Medium",
        type: "Safety",
        startDate: "2024-12-10",
        category: "Work - Safety",
        objective: "Daily safety tip delivery system",
        notes: "Implemented automated system for distributing daily safety tips with Sunny character branding",
        completion: 100
    },
    {
        id: 6,
        name: "Safety Celebration - Achievement Recognition",
        status: "Not Started",
        priority: "High",
        type: "Safety",
        startDate: "2024-12-01",
        category: "Work - Safety",
        objective: "Team safety milestone celebration",
        notes: "Planning celebration event to recognize team safety achievements and milestone completion",
        completion: 0
    },
    {
        id: 7,
        name: "Safety Training Materials",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2024-11-20",
        category: "Work - Safety",
        objective: "Comprehensive training resource development",
        notes: "Developed training materials covering all safety protocols, procedures, and best practices",
        completion: 100
    },
    {
        id: 8,
        name: "Safety Checklist",
        status: "Completed",
        priority: "Medium",
        type: "Safety",
        startDate: "2024-11-15",
        category: "Work - Safety",
        objective: "Daily safety verification system",
        notes: "Created comprehensive checklist for daily safety inspections and compliance verification",
        completion: 100
    },
    {
        id: 9,
        name: "Safety Incident Report Form",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2024-11-05",
        category: "Work - Safety",
        objective: "Standardized incident reporting system",
        notes: "Created digital form for consistent incident reporting with automatic routing and tracking",
        completion: 100
    },
    {
        id: 10,
        name: "Safety Monthly Report",
        status: "Completed",
        priority: "Medium",
        type: "Safety",
        startDate: "2024-11-01",
        category: "Work - Safety",
        objective: "Regular safety performance reporting",
        notes: "Established monthly reporting system tracking safety metrics, incidents, and improvement areas",
        completion: 100
    },
    {
        id: 11,
        name: "Safety Policy and Procedures",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2024-10-20",
        category: "Work - Safety",
        objective: "Comprehensive safety policy framework",
        notes: "Created detailed policy document covering all safety procedures, protocols, and compliance requirements",
        completion: 100
    },
    {
        id: 12,
        name: "Safety Emergency Response Plan",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2024-09-25",
        category: "Work - Safety",
        objective: "Comprehensive emergency procedures",
        notes: "Created detailed emergency response procedures covering all potential workplace emergencies",
        completion: 100
    },
    {
        id: 13,
        name: "Safety Banner - Temperature Awareness Update",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-07-14",
        category: "Work - Safety",
        objective: "Updated safety banner with summer temperature messaging",
        notes: "Added heat illness prevention content, hydration reminders, and updated Sunny's messaging for summer safety awareness",
        completion: 100
    },
    {
        id: 14,
        name: "Sunny the Safety Duck - Enhanced Interactive Features",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-07-15",
        category: "Work - Safety",
        objective: "Enhanced Sunny with advanced weather system, improved animations, and interactive personality features",
        notes: "Added 6-environment weather system (sunny, rainy, snowy, stormy, autumn, spring), enhanced flower personality with mood system, improved visual effects with better gradients and shadows, added weather-specific messaging, enhanced safety tip rotation system, and improved overall user experience with smooth transitions",
        completion: 100
    },
    {
        id: 15,
        name: "Project Tracker Development with Claude AI",
        status: "Completed",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-07-15",
        category: "Work - Web Dev",
        objective: "Rebuilt project tracker from Notion export into modern web application with proper file separation",
        notes: "Collaborated with Claude AI to convert basic Notion HTML export into professional project tracking system. Separated code into organized files (index.html, styles.css, script.js, data.js, README.md), implemented responsive design with card and table views, added filtering and search functionality, created GitHub-ready file structure, and established maintainable data management system",
        completion: 100
    },
    {
        id: 16,
        name: "King Lincoln Columbus Safety Widgets",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-07-16",
        category: "Work - Web Dev",
        objective: "Create Columbus-themed safety widgets for King Lincoln medical center",
        notes: "Developed comprehensive set of Columbus-themed safety widgets including safety leads, liaisons, CPR training, location info, pharmacy details, and building showcase. Used scarlet red/gray Buckeye colors, Ohio branding, and professional healthcare styling. Created compact, responsive widgets with hover effects and consistent branding across all components.",
        completion: 100
    },
    {
        id: 17,
        name: "Short North Ohio Safety Widgets",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-07-10",
        category: "Work - Web Dev",
        objective: "Create Ohio-themed safety widgets for Short North medical center",
        notes: "Developed comprehensive set of Ohio-themed safety widgets using teal/navy color scheme with Ohio State red accents. Created safety information hub, safety leads directory, safety liaisons, CPR training, location widgets, pharmacy details, and building showcase banner with Sunny the Safety Duck. All widgets designed with 100% width, responsive layouts, and consistent Ohio branding.",
        completion: 100
    },
    {
        id: 18,
        name: "Alert Media FAQ Revamp",
        status: "Completed",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-07-15",
        category: "Work - Web Dev",
        objective: "Revamp Alert Media FAQ section with modern styling and improved user experience",
        notes: "Originally created Alert Media FAQ section on July 15th. Completely redesigned on July 18th with modern CSS techniques including gradient backgrounds, glassmorphism effects, card-based layout, hover animations, and responsive grid design. Added CSS Grid for responsive columns, smooth transitions, loading animations, and ensured 100% width compatibility for widget integration. Fixed button text visibility issues and implemented mobile-friendly responsive design. Revamp Date: July 18, 2025",
        completion: 100
    }
];
