const projects = [
    {
        id: 1,
        name: "Committee Files",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-01-10",
        category: "Work - Safety",
        objective: "Organize and digitize all committee documentation",
        notes: "Successfully organized and digitized all safety committee files for easy access and reference.",
        completion: 100
    },
    {
        id: 2,
        name: "Safety Banner",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-01-15",
        category: "Work - Safety",
        objective: "Create prominent safety messaging display",
        notes: "Enhanced the rotating safety banner with temperature-specific content including heat illness prevention, hydration reminders, cooling station locations, and updated Sunny's messaging for summer safety awareness. Added OSHA heat safety guidelines and created mobile-responsive temperature alert styling.",
        completion: 100
    },
    {
        id: 3,
        name: "Safety Emergency Response Plan",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-01-22",
        category: "Work - Safety",
        objective: "Develop comprehensive emergency response procedures",
        notes: "Created detailed emergency response protocols for all safety scenarios.",
        completion: 100
    },
    {
        id: 4,
        name: "Safety Policy and Procedures",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-01-25",
        category: "Work - Safety",
        objective: "Document all safety policies and procedures",
        notes: "Comprehensive documentation of all safety policies and standard procedures.",
        completion: 100
    },
    {
        id: 5,
        name: "Safety Monthly Report",
        status: "Completed",
        priority: "Medium",
        type: "Safety",
        startDate: "2025-02-01",
        category: "Work - Safety",
        objective: "Monthly safety performance reporting system",
        notes: "Established monthly reporting system for safety metrics and performance tracking.",
        completion: 100
    },
    {
        id: 6,
        name: "Safety Incident Report Form",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-02-05",
        category: "Work - Safety",
        objective: "Digital incident reporting system",
        notes: "Created comprehensive digital form for safety incident reporting and tracking.",
        completion: 100
    },
    {
        id: 7,
        name: "Short North Map Redo",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-02-10",
        category: "Work - Safety",
        objective: "Complete redesign of Short North location map",
        notes: "Fully redesigned and updated the Short North location safety map with current information.",
        completion: 100
    },
    {
        id: 8,
        name: "Sunny's Safety Tips",
        status: "Completed",
        priority: "Medium",
        type: "Safety",
        startDate: "2025-02-10",
        category: "Work - Safety",
        objective: "Daily safety tip delivery system",
        notes: "Implemented daily safety tips featuring Sunny the Safety Duck for staff engagement.",
        completion: 100
    },
    {
        id: 9,
        name: "Safety Checklist",
        status: "Completed",
        priority: "Medium",
        type: "Safety",
        startDate: "2025-02-15",
        category: "Work - Safety",
        objective: "Comprehensive safety checklist development",
        notes: "Created detailed safety checklist for regular facility inspections and compliance.",
        completion: 100
    },
    {
        id: 10,
        name: "Sunny Homepage",
        status: "Ongoing",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-02-15",
        category: "Work - Web Dev",
        objective: "Interactive Sunny the Safety Duck homepage",
        notes: "Enhanced Sunny with a 6-environment weather system (sunny, rainy, snowy, stormy, autumn, spring), added flower personality with mood system, improved animations and visual effects, and created weather-specific safety messaging.",
        completion: 85
    },
    {
        id: 11,
        name: "Safety Training Materials",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-02-20",
        category: "Work - Safety",
        objective: "Comprehensive safety training content development",
        notes: "Developed complete set of safety training materials for all staff levels and departments.",
        completion: 100
    },
    {
        id: 12,
        name: "Safety Celebration",
        status: "Not Started",
        priority: "Low",
        type: "Safety",
        startDate: "2025-03-01",
        category: "Work - Safety",
        objective: "Employee safety achievement recognition program",
        notes: "Planned program to recognize and celebrate safety achievements and milestones.",
        completion: 0
    },
    {
        id: 13,
        name: "EAP Page Redo",
        status: "Completed",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-03-15",
        category: "Work - Web Dev",
        objective: "Final checkup",
        notes: "Design, content and layout redone",
        completion: 100
    },
    {
        id: 14,
        name: "Safety Team Profiles",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-03-20",
        category: "Web Development",
        objective: "Upload final images",
        notes: "Pictures and intros completed",
        completion: 100
    },
    {
        id: 15,
        name: "Safety Section Q & A",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-04-01",
        category: "Work - Safety",
        objective: "Monitor for new questions",
        notes: "Live and ready to maintain",
        completion: 100
    },
    {
        id: 16,
        name: "Safe and Sound Page",
        status: "Completed",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-04-04",
        category: "Work - Web Dev",
        objective: "Enhance resource list",
        notes: "Initial version done",
        completion: 100
    },
    {
        id: 17,
        name: "Tornado Drill Procedures",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-04-05",
        category: "Work - Safety",
        objective: "Revise outdated steps",
        notes: "Needs tweaking for clarity",
        completion: 100
    },
    {
        id: 18,
        name: "Covid Guidelines SubPage",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-04-17",
        category: "Work - Web Dev",
        objective: "Replace outdated PDF with redesigned subpage",
        notes: "Replaced the outdated PDF with a brand-new, fully redesigned subpage. The content has been streamlined, styled, and professionally tailored to emphasize safety protocols. It's now visually engaging, easy to follow, and perfectly aligned with our health and safety standards.",
        completion: 100
    },
    {
        id: 19,
        name: "Incident Reporting SubPage",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-04-19",
        category: "Work - Web Dev",
        objective: "Centralize incident reporting for staff",
        notes: "Created a new Incident Reporting (IR) sub page to centralize and streamline reporting for staff. Designed with a clean, professional layout and animated widget for improved user engagement.",
        completion: 100
    },
    {
        id: 20,
        name: "Revamped Mission Statement Page",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-04-21",
        category: "Work - Web Dev",
        objective: "Design styled safety mission statement widget",
        notes: "Designed and implemented a fully styled safety mission statement widget using brand-aligned colors and modern formatting to enhance visual impact and clarity.",
        completion: 100
    },
    {
        id: 21,
        name: "Team Webpage Revamp",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-04-24",
        category: "Work - Web Dev",
        objective: "Build responsive Safety Team subpage",
        notes: "Build and launch a fully responsive, interactive Safety Team subpage with two widget rows featuring 6 total team bios, styled consistently and aligned for engagement and clarity.",
        completion: 100
    },
    {
        id: 22,
        name: "Financial Workbook PWA Development",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-06-30",
        category: "Work - Web Dev",
        objective: "Build comprehensive financial management Progressive Web App",
        notes: "Built a complete React Progressive Web App with bill tracking, income management, real-time calculations, mobile-responsive design, PWA installation, professional Git workflow, and Vercel deployment with automatic updates. Created a production-ready financial application deployed at https://financial-workbook.vercel.app/.",
        completion: 100
    },
    {
        id: 23,
        name: "King Lincoln Columbus Safety Widgets",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-07-16",
        category: "Work - Web Dev",
        objective: "Create Columbus-themed safety widgets for King Lincoln location",
        notes: "Created a complete set of Columbus-themed safety widgets including safety leads, liaisons, CPR training, location information, pharmacy details, and building showcase with professional Buckeye colors and responsive design.",
        completion: 100
    },
    {
        id: 24,
        name: "Short North Ohio Safety Widgets",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-07-10",
        category: "Work - Web Dev",
        objective: "Create Ohio-themed safety widgets for Short North location",
        notes: "Created a complete set of Ohio-themed safety widgets using teal/navy color scheme with Ohio State red accents. Built safety information hub, safety leads directory, liaisons, CPR training, location info, pharmacy details, and building showcase banner featuring Sunny the Safety Duck.",
        completion: 100
    },
    {
        id: 25,
        name: "Project Tracker Development",
        status: "Completed",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-07-15",
        category: "Work - Web Dev",
        objective: "Rebuild Notion tracker into professional web application",
        notes: "Converted basic Notion HTML export into professional web application with proper file separation (HTML, CSS, JavaScript, data), responsive design, interactive filtering, search functionality, and GitHub-ready structure.",
        completion: 100
    },
    {
        id: 26,
        name: "Alert Media FAQ Revamp",
        status: "Completed",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-07-15",
        category: "Work - Web Dev",
        objective: "Redesign FAQ section with modern styling",
        notes: "Originally created the FAQ section on July 15th, then completely redesigned it on July 18th with modern CSS techniques including gradient backgrounds, glassmorphism effects, card-based layout, hover animations, CSS Grid for responsive design, and fixed button text visibility issues.",
        completion: 100
    },
    {
        id: 27,
        name: "Sunny the Safety Duck - Enhanced Interactive Features",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-07-15",
        category: "Work - Safety",
        objective: "Enhance Sunny with interactive weather system and mood features",
        notes: "Enhanced Sunny with a 6-environment weather system (sunny, rainy, snowy, stormy, autumn, spring), added flower personality with mood system, improved animations and visual effects, and created weather-specific safety messaging.",
        completion: 100
    },
    {
        id: 28,
        name: "Safety Safari: Multi-Location Educational Web Platform",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-07-01",
        category: "Safety Education",
        objective: "Develop comprehensive, location-specific safety education web platform featuring a safety mascot across multiple Ohio cities with unified branding and scalable template system",
        notes: "Created multiple HTML templates and pages for different locations (Akron, Cincinnati, Dayton, Short North Columbus) with consistent safety mascot branding. Built scalable location template system that can be easily adapted for new cities. Implemented responsive design that works across different devices with location-relevant safety messaging.",
        completion: 100
    },
    {
        id: 29,
        name: "Equitas Health Location Maps - Compliance & Uniformity Redesign",
        status: "In Progress",
        priority: "High",
        type: "Map Design",
        startDate: "2025-07-15",
        category: "Compliance",
        objective: "Redesign all Equitas Health location maps to ensure compliance standards and create uniform design consistency across all clinic locations",
        notes: "Major redesign project to bring all location maps up to compliance standards with uniform design principles. Completed: King Lincoln, Short North, and Akron locations are fully redesigned and compliant. Remaining work: Dayton and Cincinnati locations need to be completed to match the new standardized design.",
        completion: 60
    },
    {
        id: 30,
        name: "Sunny the Safety Duck Birthday Widget",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-08-14",
        category: "Work - Web Dev",
        objective: "Create interactive birthday widget featuring Sunny the Safety Duck for Mission Central",
        notes: "Developed safety-themed birthday widget with admin-controlled name management for Equitas Health's Mission Central page. Features Sunny the Safety Duck mascot, safety color scheme, contact info for Mike Butcher, and celebration animations. Widget is admin-controlled for professional deployment. Ongoing updates with birthdays as needed.",
        completion: 100
    }
];