// Complete projects data from your Notion tracker
const projects = [
    {
        id: 1,
        name: "Short North Map Redo",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-02-10",
        dueDate: "2025-02-24",
        category: "Work - Safety",
        objective: "Completed Projects",
        notes: "Created 82 custom safety maps and posted site-wide",
        actions: "Maintain & update as needed",
        completion: 100
    },
    {
        id: 2,
        name: "EAP Page Redo",
        status: "Completed",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-03-15",
        dueDate: "2025-04-05",
        category: "Work - Web Dev",
        objective: "Final checkup",
        notes: "Design, content and layout redone",
        actions: "Archive version history",
        completion: 100
    },
    {
        id: 3,
        name: "Safety Team Profiles",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-03-20",
        dueDate: "2025-04-10",
        category: "Web Development",
        objective: "Upload final images",
        notes: "Pictures and intros completed",
        actions: "Maintain profiles monthly",
        completion: 100
    },
    {
        id: 4,
        name: "Safety Section Q & A",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-04-01",
        dueDate: "2025-04-10",
        category: "Work - Safety",
        objective: "Monitor for new questions",
        notes: "Live and ready to maintain",
        actions: "Update daily",
        completion: 100
    },
    {
        id: 5,
        name: "Alert Media Page",
        status: "Completed",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-04-01",
        dueDate: "2025-04-08",
        category: "Work - Web Dev",
        objective: "Publish final version",
        notes: "Live and working properly",
        actions: "Monitor feedback",
        completion: 100
    },
    {
        id: 6,
        name: "CPR Training Page",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-04-02",
        dueDate: "2025-04-12",
        category: "Work - Web Dev",
        objective: "Confirm registration form",
        notes: "Fully functional with training info",
        actions: "Schedule calendar updates",
        completion: 100
    },
    {
        id: 7,
        name: "Equitas Locations Nav",
        status: "Completed",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-04-03",
        dueDate: "2025-07-01",
        category: "Work - Web Dev",
        objective: "Initial Page Completed",
        notes: "Navigation section live",
        actions: "Consistently add new information",
        completion: 100
    },
    {
        id: 8,
        name: "Safe and Sound Page",
        status: "Completed",
        priority: "Medium",
        type: "Web Development",
        startDate: "2025-04-04",
        dueDate: "2025-04-10",
        category: "Work - Web Dev",
        objective: "Enhance resource list",
        notes: "Initial version done",
        actions: "Maintain Page - Check for Updates",
        completion: 100
    },
    {
        id: 9,
        name: "Tornado Drill Procedures",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-04-05",
        dueDate: "2025-04-10",
        category: "Work - Safety",
        objective: "Revise outdated steps",
        notes: "Needs tweaking for clarity",
        actions: "Completed and monitoring for new information to be added",
        completion: 100
    },
    {
        id: 10,
        name: "Sunny Homepage",
        status: "Ongoing",
        priority: "High",
        type: "Web Development",
        startDate: "2025-04-10",
        dueDate: "",
        category: "Web Development",
        objective: "Added a Brief Introduction and a Coming Soon feature to Sunny - 4.14.25",
        notes: "Live and ready to maintain / add new features as they come",
        actions: "Daily Code Check for Bugs",
        completion: 100
    },
    {
        id: 11,
        name: "Sunny Check-In Poll",
        status: "On Hold",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-04-14",
        dueDate: "",
        category: "Web Development",
        objective: "Stages of Coding",
        notes: "Revisiting code and structure - not working as intended",
        actions: "Redoing the entire structure",
        completion: 10
    },
    {
        id: 12,
        name: "General Safety Guidelines",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-04-16",
        dueDate: "2025-04-16",
        category: "Work - Web Dev",
        objective: "Changed the format and structure of General Safety Guidelines content. Added styling for more readability",
        notes: "Live and working properly",
        actions: "Maintain Daily - Check for Bugs",
        completion: 100
    },
    {
        id: 13,
        name: "Covid Guidelines SubPage",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-04-17",
        dueDate: "2025-04-17",
        category: "Work - Web Dev",
        objective: "Replaced the outdated PDF with a brand-new, fully redesigned subpage",
        notes: "The content has been streamlined, styled, and professionally tailored to emphasize safety protocols. It's now visually engaging, easy to follow, and perfectly aligned with our health and safety standards—ensuring it not only informs but also catches attention. Fully functional with training info",
        actions: "Maintain and update as needed",
        completion: 100
    },
    {
        id: 14,
        name: "Incident Reporting SubPage",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-04-19",
        dueDate: "2025-04-25",
        category: "Work - Web Dev",
        objective: "Created a new Incident Reporting (IR) sub page to centralize and streamline reporting for staff. Designed with a clean, professional layout and animated widget for improved user engagement",
        notes: "Ongoing work will focus on maintaining functionality, monitoring feedback, and iterating design based on user needs",
        actions: "Next steps include finalizing the widget's interactive features and linking it to our internal database",
        completion: 100
    },
    {
        id: 15,
        name: "Revamped Mission Statement Page",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-04-21",
        dueDate: "2025-04-21",
        category: "Work - Web Dev",
        objective: "Designed and implemented a fully styled safety mission statement widget using brand-aligned colors and modern formatting to enhance visual impact and clarity",
        notes: "Maintain styling consistency, monitor readability across devices, and explore future enhancements like icon integration",
        actions: "Test mobile responsiveness and make any necessary layout adjustments",
        completion: 100
    },
    {
        id: 16,
        name: "Team Webpage Revamp",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-04-24",
        dueDate: "2025-05-09",
        category: "Work - Web Dev",
        objective: "Build and launch a fully responsive, interactive Safety Team subpage with two widget rows featuring 6 total team bios, styled consistently and aligned for engagement and clarity",
        notes: "All bios are now fully implemented using HTML/CSS in two separate widgets to prevent layout conflicts. Cards include name, pronouns, titles, quotes, and HR links. Fixed height alignment and scrollable inner content were applied for visual consistency. Color palette and interactions follow Equitas Health's safety branding",
        actions: "Add alt-text enhancements for accessibility, Test mobile responsiveness across breakpoints, Explore optional animation triggers (e.g. hover effects, fade-in, modal bios), Draft version for team feedback and future expansion (new hires, role changes)",
        completion: 100
    },
    {
        id: 17,
        name: "Radio Log Web Page",
        status: "Not Started",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-04-24",
        dueDate: "",
        category: "Work- Web Dev",
        objective: "NA",
        notes: "NA",
        actions: "NA",
        completion: 0
    },
    {
        id: 18,
        name: "Dayton Map Nato Project",
        status: "Completed",
        priority: "High",
        type: "Safety",
        startDate: "2025-05-01",
        dueDate: "2025-05-10",
        category: "Work - Map Design",
        objective: "Mapping NATO event zone in Dayton with clear boundary and Equitas Health location overlay",
        notes: "Maintain styling consistency, monitor readability across devices, and explore future enhancements",
        actions: "Next, export visual map with distance marked and submit to leadership",
        completion: 100
    },
    {
        id: 19,
        name: "Shelter in Place Page",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-05-01",
        dueDate: "2025-05-01",
        category: "Work - Web Dev",
        objective: "Deploy an interactive, visually engaging tornado shelter-in-place widget to communicate emergency procedures clearly and drive staff to the full guidance document",
        notes: "Full-width responsive layout implemented, Collapsible sections added for readability, Linked PDF guidance via CTA button",
        actions: "Monitor page display across devices, Confirm accessibility compliance, Promote internal awareness of the update",
        completion: 100
    },
    {
        id: 20,
        name: "C.R.A.S.E Training Subpage",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-05-02",
        dueDate: "2025-05-15",
        category: "Work - Web Dev",
        objective: "Ensure widget displays cleanly and responsively on live site. Test across devices and browsers",
        notes: "Custom widget for Short North CRASE training photos. Features logo, header, description, and responsive fade carousel. Styling finalized",
        actions: "✅ Submit for final approval ⏳ Monitor display/performance 🔁 Add captions / download options 💬 Replicate for other sites",
        completion: 100
    },
    {
        id: 21,
        name: "Team Webpage Photo Carousel",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-05-02",
        dueDate: "2025-05-13",
        category: "Work - Web Dev",
        objective: "Implement a responsive image carousel at the top of the Safety Team page to showcase team photos and increase visual engagement",
        notes: "Successfully integrated a custom-built image carousel into the existing header widget. Styled carousel to match the Equitas brand (colors, shapes, animation). Implemented automatic scroll and dot navigation. Logic hides carousel controls when only one photo is present. Carousel is now live and ready for expansion as more team photos are captured",
        actions: "Add more group/team photos to the carousel as they become available, Test carousel responsiveness on mobile/tablet devices, Explore adding captions or hover effects for context or fun quotes, Collect feedback from staff on how the new section feels and performs",
        completion: 100
    },
    {
        id: 22,
        name: "Safety Tips, Whats New, Information & Resources",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-05-07",
        dueDate: "2025-05-13",
        category: "Work - Web Dev",
        objective: "",
        notes: "",
        actions: "",
        completion: 0
    },
    {
        id: 23,
        name: "Fire Drill Webpage",
        status: "Ongoing",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-05-09",
        dueDate: "",
        category: "Work - Web Dev",
        objective: "NA",
        notes: "NA",
        actions: "",
        completion: 0
    },
    {
        id: 24,
        name: "Safety Banner Awareness",
        status: "Ongoing",
        priority: "High",
        type: "Safety",
        startDate: "2025-05-23",
        dueDate: "",
        category: "Work - Web Dev",
        objective: "Launch and maintain a rotating weekly safety awareness banner on the website using Sunny the Safety Duck. Updated with temperature safety messaging for summer awareness",
        notes: "Built using HTML, CSS, and animation-ready layout. Features a 3-column flexbox design: Sunny 🐥 | Quote 💬 | Content 📘. Includes animated speech bubble and responsive mobile stacking. Weekly updates include: topic title, safety message, Sunny's quote, and OSHA resource link. Recently updated with temperature safety content including heat illness prevention, hydration reminders, and workplace cooling measures. Tested and optimized for desktop + mobile",
        actions: "[ ] Add next week's awareness topic by Monday [ ] Confirm new quote and OSHA reference [ ] Drop in updated code block to widget section [ ] Notify comms/team when new banner goes live [ ] Continue temperature safety messaging through summer months",
        completion: 100
    },
    {
        id: 25,
        name: "Akron Safety Page Revamp",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-06-02",
        dueDate: "",
        category: "Work - Web Dev",
        objective: "Modernize the Akron safety page with branded styling and interactive components consistent with the Equitas homepage and safety hub experience",
        notes: "Rebuilt the 'Welcome' widget using orange accent card styling. Styled CPR Training sections with hover and fade-in animations. Created a fully responsive Akron Safety Banner with background image, live date, and animated Sunny (transparent PNG). Integrated the new transparent Sunny image titled 'Safety Duck 2.png'. Upgraded Safety Leads and Liaison widgets with staff photos, profile links, and hover effects. Matched all widget styling to the homepage hover and shadow effects. Verified internal image and profile links from Mission Central. Visual spacing, contrast, and accessibility improvements applied throughout the page",
        actions: "Monitor page performance and user feedback. Consider expanding design patterns to other location pages",
        completion: 100
    },
    {
        id: 26,
        name: "CPR Signup Widget Styling & Locations Project",
        status: "Completed",
        priority: "High",
        type: "Web Development",
        startDate: "2025-06-21",
        dueDate: "",
        category: "Work - Web Dev",
        objective: "Revamp all CPR training signup sections to match Equitas Safety Tip branding, ensuring consistent visual styling, improved accessibility, and easier user navigation across all location-specific widgets",
        notes: "The CPR signup section was rebuilt using a Google Form with automated confirmation emails via Google Apps Script. Submissions now go directly to a roster in Google Sheets. The main signup widget was restyled with Equitas branding: orange left border, soft yellow background, and Segoe UI font. The image now links to the form in a new tab. All location-specific widgets (King-Lincoln, Cincinnati, Dayton, Akron) were updated to match, made full-width, and had past April dates removed. Emojis were replaced with plain text for compatibility, and titles/content were cleaned up for clarity",
        actions: "Add remaining CPR location widgets if needed, including Portsmouth and Athens. Explore building a collapsible or accordion-style layout for mobile-friendliness. Consider adding 'Add to Google Calendar' links beside each date if supported. Optionally combine all widgets into a central CPR landing page. Once confirmed, update the admin email recipient from Mike to Matt in the confirmation system",
        completion: 100
    },
    {
        id: 27,
        name: "Cincinnati Location Page Revamp",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-07-01",
        dueDate: "2025-07-01",
        category: "Work - Web Dev",
        objective: "Complete the redesign of the Cincinnati location webpage with updated visuals, staff widget, and improved layout consistency",
        notes: "The original banner image was too grainy and zoomed in, so it was replaced with a clearer version. Text alignment was corrected from center to left to match the Akron layout. The color scheme was adjusted to reflect Cincinnati's style while staying visually aligned with other locations. The Safety Liaison widget for Chris Salguero was added and linked to the HR directory. Hover effects and responsive design were applied to ensure consistency with other location pages. A new banner title is still needed to provide a warm welcome message",
        actions: "Finalize a new warm welcome banner title for Cincinnati. Complete testing for layout responsiveness on both desktop and mobile. Add the final image-only widget and confirm its placement. Publish the completed changes and send out a notification to the leadership team",
        completion: 100
    },
    {
        id: 28,
        name: "CPR Feedback",
        status: "Completed",
        priority: "Low",
        type: "Web Development",
        startDate: "2025-07-01",
        dueDate: "2025-07-01",
        category: "Web Dev",
        objective: "Launch the finalized CPR Class Feedback widget with animated Sunny using the updated PNG. Ensure styling matches the main CPR sign-up banner and Sunny is positioned correctly",
        notes: "Replaced the previous Sunny with a transparent version. Positioned Sunny to the bottom-right of the widget and added a bounce animation. Styling matches the Akron CPR widget with proper text alignment, branding colors, and mobile-friendly layout. Final adjustments included reducing Sunny's right margin to bring her closer to the text",
        actions: "Verify widget placement on the live site and confirm visibility across screen sizes. Optional: Flip Sunny horizontally to face the content or add hover effects for interactivity. Monitor feedback form submissions and consider adding a 'Thank You' animation or banner after submission",
        completion: 100
    }
];